// <auto-generated />
using System;
using ERM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523152320_ClothinModelIsDeleted")]
    partial class ClothinModelIsDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ERM.Core.Domain.Entities.ClothingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IroningPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SewingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ClothingModels");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CutterEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeclaredQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CutterEmployeeId");

                    b.ToTable("CutBatches");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClothingModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CutBatchId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CutPricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FabricColorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssuedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClothingModelId");

                    b.HasIndex("CutBatchId");

                    b.HasIndex("FabricColorId");

                    b.ToTable("CutBatchItems");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Cutter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Cutters");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.FabricColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FabricColors");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Ironer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Ironers");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.PayrollAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PayrollAdjustments");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Seamstress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Seamstresses");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.WorkAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CutBatchItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDate");

                    b.HasIndex("CutBatchItemId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeekNumber", "Year");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatch", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.Employee", "CutterEmployee")
                        .WithMany()
                        .HasForeignKey("CutterEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CutterEmployee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatchItem", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.ClothingModel", "ClothingModel")
                        .WithMany()
                        .HasForeignKey("ClothingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERM.Core.Domain.Entities.CutBatch", "CutBatch")
                        .WithMany("Items")
                        .HasForeignKey("CutBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERM.Core.Domain.Entities.FabricColor", "FabricColor")
                        .WithMany()
                        .HasForeignKey("FabricColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClothingModel");

                    b.Navigation("CutBatch");

                    b.Navigation("FabricColor");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Cutter", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.Employee", "Employee")
                        .WithOne("Cutter")
                        .HasForeignKey("ERM.Core.Domain.Entities.Cutter", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Ironer", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.Employee", "Employee")
                        .WithOne("Ironer")
                        .HasForeignKey("ERM.Core.Domain.Entities.Ironer", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.PayrollAdjustment", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Seamstress", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.Employee", "Employee")
                        .WithOne("Seamstress")
                        .HasForeignKey("ERM.Core.Domain.Entities.Seamstress", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.WorkAssignment", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.CutBatchItem", "CutBatchItem")
                        .WithMany()
                        .HasForeignKey("CutBatchItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERM.Core.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CutBatchItem");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Cutter");

                    b.Navigation("Ironer");

                    b.Navigation("Seamstress");
                });
#pragma warning restore 612, 618
        }
    }
}
