// <auto-generated />
using System;
using ERM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510153056_CutBatchUpdate")]
    partial class CutBatchUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ERM.Core.Domain.Entities.ClothingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClothingModels");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeclaredQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CutBatches");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClothingModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CutBatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClothingModelId");

                    b.HasIndex("CutBatchId");

                    b.ToTable("CutBatchItems");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Seamstress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Seamstresses");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.WorkAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CutBatchItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeamstressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDate");

                    b.HasIndex("CutBatchItemId");

                    b.HasIndex("SeamstressId");

                    b.HasIndex("WeekNumber", "Year");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatchItem", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.ClothingModel", "ClothingModel")
                        .WithMany()
                        .HasForeignKey("ClothingModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERM.Core.Domain.Entities.CutBatch", "CutBatch")
                        .WithMany("Items")
                        .HasForeignKey("CutBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClothingModel");

                    b.Navigation("CutBatch");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Seamstress", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.Employee", "Employee")
                        .WithOne("Seamstress")
                        .HasForeignKey("ERM.Core.Domain.Entities.Seamstress", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.WorkAssignment", b =>
                {
                    b.HasOne("ERM.Core.Domain.Entities.CutBatchItem", "CutBatchItem")
                        .WithMany()
                        .HasForeignKey("CutBatchItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERM.Core.Domain.Entities.Seamstress", "Seamstress")
                        .WithMany()
                        .HasForeignKey("SeamstressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CutBatchItem");

                    b.Navigation("Seamstress");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.CutBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERM.Core.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Seamstress");
                });
#pragma warning restore 612, 618
        }
    }
}
